version: '3.7'

services:
  app:
    container_name: natural_selection
    build:
      context: ./web_app
    volumes:
      - ./web_app:/usr/src/web_app
    ports:
      - "5000:5000"
    env_file:
      - ./.env
